name:                cinetv2public
version:             0.2
github:              githubuser/cinetv2public
license:             GPL-3
author:              Konstantinos Lambrou-Latreille
maintainer:          klambroulatreille@cinematheque.qc.ca
copyright:           2020 Cinémathèque québécoise

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/cinetv-migration#readme>

dependencies:
- base >= 4.11 && < 10
- cinetv4h
- unliftio
- text
- directory
- filepath
- persistent-sqlite
- esqueleto
- resource-pool
- regex

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

# library:
#   source-dirs: src

executables:
  cinetv2public-exe:
    main:                Main.hs
    dependencies:
    # - cinetv2public
    - docopt

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
