name:                cinetvlinking
version:             0.1.0.0
github:              githubuser/cinetvlinking
license:             BSD3
author:              Konstantinos Lambrou-Latreille
maintainer:          example@example.com
copyright:           2020 Konstantinos Lambrou-Latreille

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/cinetvlinking#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- cinetv4h
- text >= 1.2 && < 1.3
- text-icu
- either >= 5 && < 5.1
- transformers >= 0.5 && < 0.6
- directory >= 1.3 && < 1.4
- persistent
- persistent-sqlite
- esqueleto >= 3 && < 3.4
- resource-pool
- cassava >= 0.5 && < 0.6
- containers >= 0.6 && < 0.7
- tabl
- monoidal-containers
- unordered-containers >= 0.2 && < 0.3
- bytestring >= 0.10 && < 0.11
- sparql-protocol
- neat-interpolation
- http-client >= 0.6 && < 0.7
- random
- vector
- foldl
- filepath
- unliftio
- aeson
- http-client-tls
- mtl
# - hsparql

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  cinetvlinking-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - cinetvlinking
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  cinetvlinking-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - cinetvlinking
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
